development:
  backend:
    name: netlify-api
    url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: interactify/kulsviergaarden # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit

  - name: "Forside" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Forside" # Used in the UI, ie.: "New Post"
    folder: "_forside" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}




  - name: "Nyheder" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Nyheder" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Nyhed", name: "body", widget: "markdown"}
      - {label: "Kategori", name: "categories", widget: "string"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Dato", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Layout (default)", name: "layout", widget: "string", default: "default"}

  - name: "Faciliteter" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Faciliteter" # Used in the UI, ie.: "New Post"
    folder: "_faciliteter" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}

  - name: "Arrangementer" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Arrangementer" # Used in the UI, ie.: "New Post"
    folder: "_arrangementer" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}

  - name: "Om-os" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Om os" # Used in the UI, ie.: "New Post"
    folder: "_om-os" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Overskrift", name: "title", widget: "string", tagname: "h1"}
      - {label: "Indhold", name: "body", widget: "markdown"}
      - {label: "Billede", name: "content-image", widget: "image"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Layout (default)", name: "layout", widget: "string"}
      - {label: "Navn i menu", name: "menu-name", widget: "string"}
